### ISSUE TITLE
Any way to batch convert?

### ISSUE THREAD

**Issue by SuperMario20** [dbry/adpcm-xq#11]
I have multiple wav files that it would take a very long time to copy each file name in and convert them manually. Is there a command or shortcut to convert multiple?

**Comment by dbry** [comment]
There's no direct way to do that in the command-line program.

However, depending on whether you're using Linux/MacOS or Windows there are simple ways to do that using shell or batch commands. For example, in Windows, I just made this process all the .wav files in a directory and put the results in the subdirectory "out" (which I created first):

`for %i in (*.wav) do adpcm-xq "%i" "out\%i"`

Hope this helps!

**Comment by SuperMario20** [comment]
Thank you!
