### ISSUE TITLE
Encoder Bugs Bunny & Taz: Time Busters PC

### ISSUE THREAD

**Issue by rubinho146** [dbry/adpcm-xq#18]
Hello! Been using this amazing tool that has been working for converting wavs to the format that this game supports for the audio ingames since it uses IMA ADPCM 4-bit using the command: "adpcm-xq -e -r -b15 audio.wav out.wav"

However, I'm having trouble with other part of the audio, the cutscene audio where it uses somewhat the same format but has a little variant in it. (They are MONO)
Will leave here a sample and also will give here a .txth file which you can use to play the sample on Foobar2000, using the vgmstream plugin.  
https://www.foobar2000.org/download
https://www.foobar2000.org/components/view/foo_input_vgmstream

I hope this can be figured out since no other command works to have the sound play perfectly ingame.

Cheers

[audio_sample.zip](https://github.com/user-attachments/files/16913775/audio_sample.zip)

**Comment by rubinho146** [comment]
Using the IMA ADPCM encoder from [Flitskikker](https://github.com/Flitskikker/IMAADPCMEncoder/commits?author=Flitskikker) it worked.
Sorry for this small issue that I've put here.
Big cheers.

**Comment by dbry** [comment]
Okay, cool, glad you were able to get something going!

I enjoyed playing your clip...  :)
