### ISSUE TITLE
Universal Mac binary

### ISSUE THREAD

**Issue by gingerbeardman** [dbry/adpcm-xq#24]
I've built it as Universal (Intel/ARM) 64-bit. It's not signed or notarised or anything.

- [adpcm-xq.zip](https://github.com/user-attachments/files/17135573/adpcm-xq.zip) version 0.5 release

## how to
- add the line `set(CMAKE_OSX_ARCHITECTURES "arm64;x86_64" CACHE STRING "" FORCE)` 
   before `project(...)` in `CMake.txt`

## then build
1. `cmake .`
1. `make`

That's it!

`file adpcm-xq` shows

```
% file adpcm-xq
adpcm-xq: Mach-O universal binary with 2 architectures: [x86_64:Mach-O 64-bit executable x86_64] [arm64:Mach-O 64-bit executable arm64]
adpcm-xq (for architecture x86_64):	Mach-O 64-bit executable x86_64
adpcm-xq (for architecture arm64):	Mach-O 64-bit executable arm64
```

I also made a drag-and-drop GUI, if there is any interest. A file selector and a window and some text output, it converts the source to WAV and then ADPCM so that when all is done you have a folder of ADPCM files next to your sources. That app is signed, but not notarised. 

https://devforum.play.date/t/adpcm-encoder-tool-mac-only/1283/7

![4852bf1917ba5eb55efe9bef56ca6eb530828f1d_2_1248x998](https://github.com/user-attachments/assets/88af33d4-858e-48c4-aa42-366559b74ee6)

**Comment by dbry** [comment]
Thanks so much! I have updated the release...

**Comment by gingerbeardman** [comment]
Ace! I will be happy to build any future versions.
