### ISSUE TITLE
How do you use this?

### ISSUE THREAD

**Issue by phd21** [dbry/adpcm-xq#4]
Hi dbry,

I am using Linux Mint 18.2 KDE based on Ubuntu 16.04.

I downloaded your source code file. ran the "gcc" command in the readme which seems to have created an executable "adpcm-xq", but it does not seem to work, or I do not know how to use it?

I help out on the Linux Mint forum, and someone was asking how to play MTH files which apparently use the adpcm codec?

Linux Mint Forums 
https://forums.linuxmint.com/viewtopic.php?f=90&t=261483

Regards,
Phil
phd21

**Comment by dbry** [comment]
Hi Phil,

The adpcm-xq program can only convert ADPCM audio that is stored in WAV files. It converts from 4-bit ADPCM to 16-bit PCM or the other way (it auto detects what the source file is and converts to the other). Unless the source file is WAV, my program can't do anything with it.

I have never heard of MTH files, but I found a page that describes them and some utility that seems to be able to deal with them (which seem to be some proprietary format without documentation). I hope this is useful.

http://www.silogic.com/trains/ADPCM.html

BTW, that's cool you help out on the Mint forums...I've been a happy Linux Mint Mate user for many years!

Regards,
David

**Comment by phd21** [comment]
Hi Dave (dbry),

Wow, nice response time. Thank you.

I never heard of MHT files either. The console terminal command "aplay" seemed to be able to play it, though it would need tweaking.

I read that particular link but the only apps/utilities I could find are one temperamental Java application and a MS Windows exe utility. 

That's great you are using Linux Mint Mate. I have been using Linux Mint KDE 17.3 and now 18.2 for years now and I love it. I think all the Linux Mint editions are wonderful. I enjoy helping out on the forums whenever I can, regardless of which edition of Linux Mint a user is using.

Have a great night or day or both ...

Regards to you and yours,
Phil
phd21

**Comment by dbry** [comment]
Thanks Phil...same to you. Hope you got a day off today!
