### ISSUE TITLE
compilation warning on macOS X

### ISSUE THREAD

**Issue by phoddie** [dbry/adpcm-xq#8]
I recently integrated the encoder into the [Moddable SDK](https://github.com/Moddable-OpenSource/moddable). We use IMA ADPCM to reduce the flash storage requirements for audio on embedded products. Switching over to the API was straightforward and the encoder works very nicely. Thank you for the great work.

On macOS X, I ran into the smallest issue - the following warning when compiling:

```
# tools debug : cc adpcm-lib.c
/Users/hoddie/Projects/moddable/tools/adpcm-lib.c:340:19: warning: comparison of integers of different signs: 'size_t' (aka 'unsigned long') and 'int' [-Wsign-compare]
    if (inbufsize < channels * 4)
        ~~~~~~~~~ ^ ~~~~~~~~~~~~
```

I added a cast to quiet that. Since `channels` is always positive, it might make sense instead to declare it as unsigned?

**Comment by dbry** [comment]
Thanks for the heads-up on this!

Looks like a cool project; let me know if you ever need help on any audio-related stuff.

**Comment by phoddie** [comment]
Excellent. Thank you!

FWIW – It looks like it should be straightforward to integrate your embedded WavPack decoder into the Moddable SDK, but we typically play though small, inexpensive speakers where lossless quality isn't going really help. Still, your cleaner IMA ADPCM encoding does eliminate some of the crunchiness of the basic naive encoder algorithm.

**Comment by dbry** [comment]
Yeah, lossless probably wouldn't make a lot of sense. But WavPack also has a lossy mode that will give ADPCM-like quality using only about 2.5 bits per sample (instead of 4). If an application came up where a ton of canned audio was required it might be useful, but the simplicity of ADPCM can't be beat for most applications.

**Comment by phoddie** [comment]
Interesting option. Flash space is often limited -- which is what motivated support for IMA ADPCM.

It looks like the WavPack file format is streamable too -- e.g. that the read callback passed to `WavpackOpenFileInput` only reads forward.

**Comment by dbry** [comment]
In the standard WavPack library (the one here on GitHub) you can ensure that only forward reads occur by having the `can_seek()` callback return `FALSE`.

There's also another version of the decoder specifically targeting embedded systems called the [Tiny Decoder](http://www.wavpack.com/tiny_encoder.zip) which I unfortunately have not put up here yet, although it is in [Rockbox](https://github.com/Rockbox/rockbox). One of the biggest advantages of this version is that it doesn't even require malloc() and doesn't need to hold a whole WavPack block internally to decode it. Maybe this is the one you were already looking at.

**Comment by phoddie** [comment]
Yes, I was looking at the Tiny Decoder (I should have mentioned that!). It seems like that would be the place to start for an embedded target.

**Comment by dbry** [comment]
Great, I'm glad you found the tiny decoder, and yes, that would be the one to start with.

If you try it let me know if you run into trouble or have any other questions.
