### ISSUE TITLE
Only IMA variant of ADPCM supported?

### ISSUE THREAD

**Issue by deton24** [dbry/adpcm-xq#9]
My sample file: https://yadi.sk/d/BvmozCv5A73q6Q

ADPCM
Codec ID                    : 2
Duration                    : 3 min 42 s
Bit rate mode               : Constant
Bit rate                    : 352.8 kb/s
Channel(s)                  : 2 channels
Sampling rate               : 44.1 kHz
Bit depth                   : 4 bits
Stream size                 : 9.40 MiB (100%)

Some other files I saw were indeed IMA-ADPCM so probably it's different variant.
The program gives error:
"Music_Choice.wav" is not a valid .WAV file!

**Comment by dbry** [comment]
Yeah, that file is a Microsoft ADPCM file, which is kind of a more complicated variant of ADPCM that is not supported by my program (as you guessed).

I think it would be fairly easy to include more variants, and the encoding algorithm would probably scale, but it's more work than I have to invest right now.

If you're looking just to decode, all programs should have the same quality, so there's no advantage to mine. If you are looking for higher quality encoding to Microsoft ADPCM I would suggest looking at FFmpeg which does some processing similar to my program (at least the look-ahead part, but not the noise-shaping part).
